import type { IvaApiClient } from "../../api-client.js";
import type { ToolDefinition } from "../../types.js";
import { createActionTool } from "../framework.js";
import { P } from "../params.js";

export function createConferenceSessionTool(client: IvaApiClient): ToolDefinition {
  return createActionTool(
    "iva_conference_session",
    "IVA conference session management: get/find/update/delete sessions, join/leave, start/stop, timer control, recording, transcription, subtitling, media publication, invitations, public info. Clients API v2.28.12.",
    [
      "get_public_by_id", "get_public_by_params", "get_join_info",
      "get", "delete", "update", "find", "find_rooms", "find_sessions",
      "get_layout_settings", "get_free_resources", "get_join_data",
      "get_periodical_by_number", "get_periodical_by_recurrence",
      "join", "leave", "restore", "start", "stop",
      "start_timer", "stop_timer", "pause_timer",
      "start_recording", "stop_recording",
      "start_transcription", "stop_transcription",
      "start_subtitling", "stop_subtitling",
      "set_media_publication", "start_media_publication", "stop_media_publication", "delete_media_publication",
      "reject_incoming_call", "respond_on_invitation", "confirm_record_access",
    ],
    {
      conferenceSessionId: P.conferenceSessionId,
      sessionUpdate: { type: "object", description: "Conference session update data" },
      joinData: { type: "object", description: "Join conference session data" },
      invitationResponse: { type: "object", description: "Invitation response" },
      mediaPublicationData: { type: "object", description: "Media publication data" },
      conferenceSessionNumber: P.conferenceSessionNumber,
      recurrenceDate: P.recurrenceDate,
      limit: P.limit,
      offset: P.offset,
      dateFrom: P.dateFrom,
      dateTo: P.dateTo,
      sortBy: P.sortBy,
      sortDirection: P.sortDirection,
      query: P.query,
    },
    {
      get_public_by_id: { apiType: "clients", method: "GET", path: "/public/conference-sessions/{conferenceSessionId}", pathParams: ["conferenceSessionId"] },
      get_public_by_params: { apiType: "clients", method: "GET", path: "/public/conference-sessions", queryParams: ["query", "limit", "offset"] },
      get_join_info: { apiType: "clients", method: "GET", path: "/public/conference-sessions/join-info", queryParams: ["query"] },
      get: { apiType: "clients", method: "GET", path: "/conference-sessions/{conferenceSessionId}", pathParams: ["conferenceSessionId"] },
      delete: { apiType: "clients", method: "DELETE", path: "/conference-sessions/{conferenceSessionId}", pathParams: ["conferenceSessionId"] },
      update: { apiType: "clients", method: "PATCH", path: "/conference-sessions/{conferenceSessionId}", pathParams: ["conferenceSessionId"], bodyParam: "sessionUpdate" },
      find: { apiType: "clients", method: "GET", path: "/conference-sessions", queryParams: ["dateFrom", "dateTo", "limit", "offset", "sortBy", "sortDirection"] },
      find_rooms: { apiType: "clients", method: "GET", path: "/conference-sessions/rooms", queryParams: ["limit", "offset"] },
      find_sessions: { apiType: "clients", method: "GET", path: "/conference-sessions/sessions", queryParams: ["dateFrom", "dateTo", "limit", "offset", "sortBy", "sortDirection"] },
      get_layout_settings: { apiType: "clients", method: "GET", path: "/conference-sessions/{conferenceSessionId}/layout", pathParams: ["conferenceSessionId"] },
      get_free_resources: { apiType: "clients", method: "GET", path: "/conference-sessions/{conferenceSessionId}/subscriptions/free-resources", pathParams: ["conferenceSessionId"] },
      get_join_data: { apiType: "clients", method: "GET", path: "/conference-sessions/{conferenceSessionId}/join-data", pathParams: ["conferenceSessionId"] },
      get_periodical_by_number: { apiType: "clients", method: "GET", path: "/conference-sessions/periodical", queryParams: ["conferenceSessionNumber"] },
      get_periodical_by_recurrence: { apiType: "clients", method: "GET", path: "/conference-sessions/periodical-by-recurrence", queryParams: ["recurrenceDate"] },
      join: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/join", pathParams: ["conferenceSessionId"], bodyParam: "joinData" },
      leave: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/leave", pathParams: ["conferenceSessionId"], emptyBody: true },
      restore: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/restore", pathParams: ["conferenceSessionId"], emptyBody: true },
      start: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/start", pathParams: ["conferenceSessionId"], emptyBody: true },
      stop: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/stop", pathParams: ["conferenceSessionId"], emptyBody: true },
      start_timer: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/timer/start", pathParams: ["conferenceSessionId"], emptyBody: true },
      stop_timer: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/timer/stop", pathParams: ["conferenceSessionId"], emptyBody: true },
      pause_timer: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/timer/pause", pathParams: ["conferenceSessionId"], emptyBody: true },
      start_recording: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/record/start", pathParams: ["conferenceSessionId"], emptyBody: true },
      stop_recording: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/record/stop", pathParams: ["conferenceSessionId"], emptyBody: true },
      start_transcription: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/transcription/start", pathParams: ["conferenceSessionId"], emptyBody: true },
      stop_transcription: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/transcription/stop", pathParams: ["conferenceSessionId"], emptyBody: true },
      start_subtitling: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/subtitle/start", pathParams: ["conferenceSessionId"], emptyBody: true },
      stop_subtitling: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/subtitle/stop", pathParams: ["conferenceSessionId"], emptyBody: true },
      set_media_publication: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/media-publication", pathParams: ["conferenceSessionId"], bodyParam: "mediaPublicationData" },
      start_media_publication: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/media-publication/start", pathParams: ["conferenceSessionId"], emptyBody: true },
      stop_media_publication: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/media-publication/stop", pathParams: ["conferenceSessionId"], emptyBody: true },
      delete_media_publication: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/media-publication/delete", pathParams: ["conferenceSessionId"], emptyBody: true },
      reject_incoming_call: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/reject-incoming-call", pathParams: ["conferenceSessionId"], emptyBody: true },
      respond_on_invitation: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/respond-on-invitation", pathParams: ["conferenceSessionId"], bodyParam: "invitationResponse" },
      confirm_record_access: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/stopped-event-confirm-access", pathParams: ["conferenceSessionId"], emptyBody: true },
    },
    client,
  );
}