import type { IvaApiClient } from "../../api-client.js";
import type { ToolDefinition } from "../../types.js";
import { createActionTool } from "../framework.js";
import { P } from "../params.js";
import { API_VERSION } from "../../constants.js";

export function createWhiteboardTool(client: IvaApiClient): ToolDefinition {
  return createActionTool(
    "iva_whiteboard",
    `IVA whiteboard: start/stop demonstration, manage books and pages (add/delete/update/clear/copy/reorder), get whiteboard/books/pages, export to PNG, undo, save change, update cursor/demo state. Clients API ${API_VERSION}.`,
    [
      "load", "start_demo", "stop_demo", "update_cursor", "update_demo_state",
      "get_books", "add_book", "get_book_pages", "add_page",
      "get_page", "delete_book", "update_book", "delete_page",
      "clear_page", "copy_page", "reorder_pages", "save_change",
      "undo", "export_page", "export_book", "get_books_by_document",
    ],
    {
      conferenceSessionId: P.conferenceSessionId,
      bookId: P.bookId,
      pageId: P.pageId,
      documentId: P.documentId,
      bookData: { type: "object", description: "Book creation data" },
      pageData: { type: "object", description: "Page creation data" },
      bookUpdate: { type: "object", description: "Book update data" },
      changeData: { type: "object", description: "Page change data" },
      copyData: { type: "object", description: "Copy page data" },
      reorderData: { type: "object", description: "Reorder pages data" },
      cursorData: { type: "object", description: "Cursor state data" },
      demoStateData: { type: "object", description: "Demonstration state data" },
      whiteboardState: {
        type: "object",
        description: "Whiteboard view state sent as the request body: {pageId, left, top, right, bottom}. All five fields are required by the API; pageId is a whiteboard page UUID, left/top/right/bottom are integer viewport coordinates.",
      },
      limit: P.limit,
      offset: P.offset,
    },
    {
      load: { apiType: "clients", method: "GET", path: "/conference-sessions/{conferenceSessionId}/whiteboard", pathParams: ["conferenceSessionId"] },
      start_demo: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/demonstration/whiteboard/start", pathParams: ["conferenceSessionId"], bodyParam: "whiteboardState" },
      stop_demo: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/demonstration/whiteboard/stop", pathParams: ["conferenceSessionId"], emptyBody: true },
      update_cursor: { apiType: "clients", method: "PATCH", path: "/conference-sessions/{conferenceSessionId}/demonstration/whiteboard/cursor", pathParams: ["conferenceSessionId"], bodyParam: "cursorData" },
      update_demo_state: { apiType: "clients", method: "PATCH", path: "/conference-sessions/{conferenceSessionId}/demonstration/whiteboard/state", pathParams: ["conferenceSessionId"], bodyParam: "demoStateData" },
      get_books: { apiType: "clients", method: "GET", path: "/conference-sessions/{conferenceSessionId}/whiteboard/books", pathParams: ["conferenceSessionId"] },
      add_book: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/whiteboard/books", pathParams: ["conferenceSessionId"], bodyParam: "bookData" },
      get_book_pages: { apiType: "clients", method: "GET", path: "/conference-sessions/{conferenceSessionId}/whiteboard/books/{bookId}/pages", pathParams: ["conferenceSessionId", "bookId"], queryParams: ["limit", "offset"] },
      add_page: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/whiteboard/books/{bookId}/pages", pathParams: ["conferenceSessionId", "bookId"], bodyParam: "pageData" },
      get_page: { apiType: "clients", method: "GET", path: "/conference-sessions/{conferenceSessionId}/whiteboard/books/{bookId}/pages/{pageId}", pathParams: ["conferenceSessionId", "bookId", "pageId"] },
      delete_book: { apiType: "clients", method: "DELETE", path: "/conference-sessions/{conferenceSessionId}/whiteboard/books/{bookId}", pathParams: ["conferenceSessionId", "bookId"] },
      update_book: { apiType: "clients", method: "PATCH", path: "/conference-sessions/{conferenceSessionId}/whiteboard/books/{bookId}", pathParams: ["conferenceSessionId", "bookId"], bodyParam: "bookUpdate" },
      delete_page: { apiType: "clients", method: "DELETE", path: "/conference-sessions/{conferenceSessionId}/whiteboard/books/{bookId}/pages/{pageId}", pathParams: ["conferenceSessionId", "bookId", "pageId"] },
      clear_page: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/whiteboard/books/{bookId}/pages/{pageId}/clear", pathParams: ["conferenceSessionId", "bookId", "pageId"], emptyBody: true },
      copy_page: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/whiteboard/books/{bookId}/pages/copy", pathParams: ["conferenceSessionId", "bookId"], bodyParam: "copyData" },
      reorder_pages: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/whiteboard/books/{bookId}/pages/reorder", pathParams: ["conferenceSessionId", "bookId"], bodyParam: "reorderData" },
      save_change: { apiType: "clients", method: "PATCH", path: "/conference-sessions/{conferenceSessionId}/whiteboard/books/{bookId}/pages/{pageId}", pathParams: ["conferenceSessionId", "bookId", "pageId"], bodyParam: "changeData" },
      undo: { apiType: "clients", method: "POST", path: "/conference-sessions/{conferenceSessionId}/whiteboard/books/{bookId}/pages/{pageId}/undo", pathParams: ["conferenceSessionId", "bookId", "pageId"], emptyBody: true },
      export_page: { apiType: "clients", method: "GET", path: "/conference-sessions/{conferenceSessionId}/whiteboard/books/{bookId}/pages/{pageId}/export", pathParams: ["conferenceSessionId", "bookId", "pageId"] },
      export_book: { apiType: "clients", method: "GET", path: "/conference-sessions/{conferenceSessionId}/whiteboard/books/{bookId}/export", pathParams: ["conferenceSessionId", "bookId"] },
      get_books_by_document: { apiType: "clients", method: "GET", path: "/conference-sessions/{conferenceSessionId}/whiteboard/books/by-document/{documentId}", pathParams: ["conferenceSessionId", "documentId"] },
    },
    client,
    {
      load: "Load/get the current whiteboard state of a conference session (incl. pages, books, demo info).",
      start_demo: "Start whiteboard demonstration. Начать демонстрацию доски. Показать доску участникам. Requires whiteboardState: {pageId, left, top, right, bottom} (all fields required per API).",
      stop_demo: "Stop whiteboard demonstration. Остановить демонстрацию доски. Прекратить показывать доску.",
      update_cursor: "Update presenter cursor position on the whiteboard (e.g. move pointer).",
      update_demo_state: "Update whiteboard demonstration state (running/paused/scrolling etc.).",
      get_books: "Get the list of whiteboard books in the conference session.",
      add_book: "Create a new whiteboard book. Создать новую книгу (раздел) на доске.",
      get_book_pages: "Get the list of pages inside a whiteboard book (with pagination).",
      add_page: "Add a new page to a whiteboard book. Добавить страницу в книгу доски.",
      get_page: "Get a single whiteboard page by ID (full content/strokes).",
      delete_book: "Delete a whiteboard book. Удалить книгу доски.",
      update_book: "Update whiteboard book metadata (title, settings, etc.).",
      delete_page: "Delete a whiteboard page. Удалить страницу доски.",
      clear_page: "Clear all content from a whiteboard page. Очистить страницу доски.",
      copy_page: "Copy a whiteboard page (e.g. duplicate slides).",
      reorder_pages: "Reorder whiteboard pages within a book (change slide order).",
      save_change: "Save a change/patch to a whiteboard page (strokes, drawings, annotations). Сохранить изменения на странице.",
      undo: "Undo the last change on a whiteboard page. Отменить последнее действие на доске.",
      export_page: "Export a whiteboard page to PNG image.",
      export_book: "Export an entire whiteboard book (e.g. as PDF/zip of pages).",
      get_books_by_document: "Get whiteboard books associated with a given document ID.",
    },
  );
}