export const P = {
  chatRoomId: { type: "string", format: "uuid", description: "Chat room UUID" },
  conferenceSessionId: { type: "string", format: "uuid", description: "Conference session UUID" },
  conferenceId: { type: "string", format: "uuid", description: "Conference UUID" },
  profileId: { type: "string", format: "uuid", description: "Profile (user) UUID" },
  participantId: { type: "string", format: "uuid", description: "Participant UUID" },
  messageId: { type: "string", format: "uuid", description: "Message UUID" },
  documentId: { type: "string", format: "uuid", description: "Document UUID" },
  directoryId: { type: "string", format: "uuid", description: "Directory UUID" },
  resourceId: { type: "string", format: "uuid", description: "Resource UUID" },
  inquiryId: { type: "string", format: "uuid", description: "Inquiry UUID" },
  answerId: { type: "string", format: "uuid", description: "Answer UUID" },
  groupId: { type: "string", format: "uuid", description: "Group UUID" },
  companyId: { type: "string", format: "uuid", description: "Company UUID" },
  subscriptionId: { type: "string", format: "uuid", description: "Subscription UUID" },
  domainId: { type: "string", format: "uuid", description: "Domain UUID" },
  conferenceTemplateId: { type: "string", format: "uuid", description: "Conference template UUID" },
  bookId: { type: "string", format: "uuid", description: "Whiteboard book UUID" },
  pageId: { type: "string", format: "uuid", description: "Whiteboard page UUID" },
  callId: { type: "string", format: "uuid", description: "Call UUID" },
  contactId: { type: "string", format: "uuid", description: "Contact UUID" },
  forwardingId: { type: "string", format: "uuid", description: "Call forwarding rule UUID" },
  recoveryTokenId: { type: "string", format: "uuid", description: "Password recovery token UUID" },
  twoFAChallengeId: { type: "string", format: "uuid", description: "2FA challenge UUID" },
  deviceId: { type: "string", format: "uuid", description: "Device UUID" },
  presenceControlId: { type: "string", format: "uuid", description: "Presence control UUID" },
  conferenceSessionStatisticId: { type: "string", format: "uuid", description: "Conference session statistics UUID" },
  layoutId: { type: "string", format: "uuid", description: "Layout UUID" },
  destinationDirectoryId: { type: "string", format: "uuid", description: "Destination directory UUID" },
  sourceDocumentId: { type: "string", format: "uuid", description: "Source document UUID" },
  presentationOwnerParticipantId: { type: "string", format: "uuid", description: "Presentation owner participant UUID" },
  busId: { type: "string", format: "uuid", description: "Event bus UUID" },
  serializer: { type: "string", description: "Serializer name" },
  id: { type: "string", format: "uuid", description: "Entity UUID" },

  limit: { type: "integer", minimum: 0, description: "Maximum number of results" },
  offset: { type: "integer", minimum: 0, description: "Number of results to skip (pagination offset)" },
  query: { type: "string", description: "Search query string" },
  search: { type: "string", description: "Search string" },
  dateFrom: { type: "integer", description: "Start date (UNIX time in ms)" },
  dateTo: { type: "integer", description: "End date (UNIX time in ms)" },
  locale: { type: "string", description: "Locale (RU or EN)", enum: ["RU", "EN"] },

  body: { type: "object", description: "Request body (JSON object)" },
  participants: { type: "array", description: "Array of participant objects", items: { type: "object" } },
  messageIds: { type: "array", items: { type: "string", format: "uuid" }, description: "Array of message UUIDs" },
  profileIds: { type: "array", items: { type: "string", format: "uuid" }, description: "Array of profile UUIDs" },
  participantIds: { type: "array", items: { type: "string", format: "uuid" }, description: "Array of participant UUIDs" },
  ids: { type: "array", items: { type: "string", format: "uuid" }, description: "Array of UUIDs" },
  resourceIds: { type: "array", items: { type: "string", format: "uuid" }, description: "Array of resource UUIDs" },
  documentIds: { type: "array", items: { type: "string", format: "uuid" }, description: "Array of document UUIDs" },
  contactIds: { type: "array", items: { type: "string", format: "uuid" }, description: "Array of contact UUIDs" },
  userIds: { type: "array", items: { type: "string", format: "uuid" }, description: "Array of user UUIDs" },
  presenceUserIds: { type: "array", items: { type: "string", format: "uuid" }, description: "Profile IDs to get presences for" },

  name: { type: "string", description: "Name" },
  password: { type: "string", description: "Password" },
  email: { type: "string", description: "Email address" },
  phone: { type: "string", description: "Phone number in E164 format or SIP/H323/RTSP address" },
  title: { type: "string", description: "Title" },
  text: { type: "string", description: "Text content" },
  type: { type: "string", description: "Type" },
  duration: { type: "integer", description: "Duration in seconds" },
  conferenceSessionNumber: { type: "integer", description: "Conference session number" },
  recurrenceDate: { type: "integer", description: "Recurrence date (UNIX time in ms)" },
  contentType: { type: "string", description: "Content type" },
  targetProfileId: { type: "string", description: "Target profile UUID" },
  mediaState: { type: "string", description: "Media state (AUDIO/VIDEO, e.g. {\"audio\":\"RECVONLY\",\"video\":\"DISABLED\"})" },
  reaction: { type: "string", description: "Reaction type" },
  dtmf: { type: "string", description: "DTMF data" },
  layout: { type: "string", description: "Layout name or settings" },
  mediaProfile: { type: "string", description: "Media profile quality setting" },
  broadcastLanguage: { type: "string", description: "Broadcast language" },
  translationDirection: { type: "string", description: "Translation direction" },
  screenOrientation: { type: "string", description: "Screen orientation" },
  originalVolume: { type: "integer", description: "Original language volume level" },
  sortBy: { type: "string", description: "Sort field name" },
  sortDirection: { type: "string", description: "Sort direction (asc or desc)", enum: ["asc", "desc"] },
  status: { type: "string", description: "Status value" },
  enabled: { type: "boolean", description: "Enabled flag" },
  approved: { type: "boolean", description: "Approved flag" },
};