export const P = {
  chatRoomId: { type: "string", format: "uuid", description: "Chat room UUID" },
  conferenceSessionId: { type: "string", format: "uuid", description: "Conference session UUID" },
  conferenceId: { type: "string", format: "uuid", description: "Conference UUID" },
  profileId: { type: "string", format: "uuid", description: "Profile (user) UUID" },
  participantId: { type: "string", format: "uuid", description: "Participant UUID" },
  messageId: { type: "string", format: "uuid", description: "Message UUID" },
  documentId: { type: "string", format: "uuid", description: "Document UUID" },
  directoryId: { type: "string", format: "uuid", description: "Directory UUID" },
  resourceId: { type: "string", format: "uuid", description: "Resource UUID" },
  inquiryId: { type: "string", format: "uuid", description: "Inquiry UUID" },
  answerId: { type: "string", format: "uuid", description: "Answer UUID" },
  subscriptionId: { type: "string", format: "uuid", description: "Subscription UUID" },
  conferenceTemplateId: { type: "string", format: "uuid", description: "Conference template UUID" },
  bookId: { type: "string", format: "uuid", description: "Whiteboard book UUID" },
  pageId: { type: "string", format: "uuid", description: "Whiteboard page UUID" },
  contactId: { type: "string", format: "uuid", description: "Contact UUID" },
  forwardingId: { type: "string", format: "uuid", description: "Call forwarding rule UUID" },
  deviceId: { type: "string", format: "uuid", description: "Device UUID" },
  presenceControlId: { type: "string", format: "uuid", description: "Presence control UUID" },
  conferenceSessionStatisticId: { type: "string", format: "uuid", description: "Conference session statistics UUID" },
  layoutId: { type: "string", format: "uuid", description: "Layout UUID" },
  destinationDirectoryId: { type: "string", format: "uuid", description: "Destination directory UUID" },
  sourceDocumentId: { type: "string", format: "uuid", description: "Source document UUID" },
  presentationOwnerParticipantId: { type: "string", format: "uuid", description: "Presentation owner participant UUID" },
  id: { type: "string", format: "uuid", description: "Entity UUID" },

  limit: { type: "integer", minimum: 0, description: "Maximum number of results" },
  offset: { type: "integer", minimum: 0, description: "Number of results to skip (pagination offset)" },
  query: { type: "string", description: "Search query string" },
  nameContains: { type: "string", description: "Name substring filter" },
  dateFrom: { type: "integer", description: "Start date (UNIX time in ms)" },
  dateTo: { type: "integer", description: "End date (UNIX time in ms)" },

  participants: { type: "array", description: "Array of participant objects", items: { type: "object" } },
  messageIds: { type: "array", items: { type: "string", format: "uuid" }, description: "Array of message UUIDs" },
  profileIds: { type: "array", items: { type: "string", format: "uuid" }, description: "Array of profile UUIDs" },
  participantIds: { type: "array", items: { type: "string", format: "uuid" }, description: "Array of participant UUIDs" },
  resourceIds: { type: "array", items: { type: "string", format: "uuid" }, description: "Array of resource UUIDs" },
  documentIds: { type: "array", items: { type: "string", format: "uuid" }, description: "Array of document UUIDs" },
  contactIds: { type: "array", items: { type: "string", format: "uuid" }, description: "Array of contact UUIDs" },

  name: { type: "string", description: "Name" },
  email: { type: "string", description: "Email address" },
  phone: { type: "string", description: "Phone number in E164 format or SIP/H323/RTSP address" },
  conferenceSessionNumber: { type: "integer", description: "Conference session number" },
  recurrenceDate: { type: "integer", description: "Recurrence date (UNIX time in ms)" },
  mediaState: { type: "string", description: "Media state (AUDIO/VIDEO, e.g. {\"audio\":\"RECVONLY\",\"video\":\"DISABLED\"})" },
  reaction: { type: "string", description: "Reaction type" },
  dtmf: { type: "string", description: "DTMF data" },
  layout: { type: "string", description: "Layout name or settings" },
  mediaProfile: { type: "string", description: "Media profile quality setting" },
  broadcastLanguage: { type: "string", description: "Broadcast language" },
  translationDirection: { type: "string", description: "Translation direction" },
  screenOrientation: { type: "string", description: "Screen orientation" },
  originalVolume: { type: "integer", description: "Original language volume level" },
  sortBy: { type: "string", description: "Sort field name" },
  sortDirection: { type: "string", description: "Sort direction (asc or desc)", enum: ["asc", "desc"] },
};